### ISSUE TITLE
cpu doesn't support Tensorflow 

### ISSUE THREAD

**Issue by mzminhaz5683** [Mahedi-61/MIU_Fall_2019#10]
I have to install Tensorflow as it needs for keras. When I run model then it says:
![Screenshot from 2019-11-18 12-11-08](https://user-images.githubusercontent.com/52498840/69030298-507f8180-0a01-11ea-8624-3f96b90ab235.png)
It doesn't match with the tutorial of sir (part 2 - model). But the result is same.
![Screenshot from 2019-11-18 12-10-57](https://user-images.githubusercontent.com/52498840/69030525-0519a300-0a02-11ea-83e8-2dbce8a58207.png)
And when I run train.py there is no result as like sir. Is it ok ? or I have to do something. I can't go ahead without solving this.
![Screenshot from 2019-11-18 12-04-11](https://user-images.githubusercontent.com/52498840/69030603-3d20e600-0a02-11ea-8661-9f6a78d18310.png)

Please help

**Comment by Mahedi-61** [comment]
It's completely OK.
As you know, Tensorflow is a deep learning api which heavily depends on CPU and other graphics related tools & libraries  in a complicated way, therefore, it is required to be installed from source. 

As you install Tensorflow as a python package using pip3 tool some it’s functions may not be installed properly on your machine.

How to install it from source is a topic of another day. Just use this TF to submit your first prediction.

We all eagerly waiting for your position in leaderboard.

**Comment by mzminhaz5683** [comment]
Ok sir.... Thank you a lot...
