### ISSUE TITLE
problem in python 3.8

### ISSUE THREAD

**Issue by Rashed-Alom** [Mahedi-61/MIU_Fall_2019#12]
pip install opencv-python
&
pip install sklearn

this two command is not working in latest version of  python 3.8

![opencv](https://user-images.githubusercontent.com/38605227/69173317-b8c98280-0b29-11ea-8a85-6770737539ec.PNG)
![sklearn1](https://user-images.githubusercontent.com/38605227/69173318-b9621900-0b29-11ea-97c5-04a26a15271e.PNG)
![sklearn2](https://user-images.githubusercontent.com/38605227/69173324-b9faaf80-0b29-11ea-9df4-1790a1c42d54.PNG)

**Comment by Rashed-Alom** [comment]
At last I solve this problem by using the python version 3.7.4 

Thanks Minhaz vai for helping me to solve this problem...

**Comment by mzminhaz5683** [comment]
Python 3.8 has some missings in libraries........ 3.7.4 is the best pack for windows till now.... I think

**Comment by Rashed-Alom** [comment]
I agree with you ✌️
