### ISSUE TITLE
Is there any other way to fasten VMware ?

### ISSUE THREAD

**Issue by Kh-Rakib** [Mahedi-61/MIU_Fall_2019#14]
I am using VMware as a virtual platform. 

Even if all the application is closed VMware is running very slowly. 

and
I 've installed Linux mint version is that all right?

**Comment by mzminhaz5683** [comment]
any linux can handle this project. But I think it's not a good idea to use Vmware if your ram is less than 6GB (Check your Task Manager)

For test prediction may be 2.8+ GB of ram is needed while running test.py
So you need to free at least 3GB of ram to run the project.

VMware (v12) needs 700+MB ram on normal & when any os runs on it then 1.4+GB...
So if you want to use VMware then you need to free (3+1.4)~4.5GB of ram at least.

And also windows OS uses generally 200+MB of ram initially and 600+MB while running VMware.
So you need totally  (4.5+.6) ~ 5.4+GB for running this program on VMware.

Calculation of ram used varies on machine. So you have to check manually for you PC... Thanks

**Comment by Mahedi-61** [comment]
You can use your Windows machine as long as you can successfully install 
Python, Tensorflow and other necessary libraries. 

@mzminhaz5683  wrote a nice [article](https://github.com/Mahedi-61/MIU_Fall_2019/issues/11) about steps required to setup Windows machine for work. You can try it first. 

However, you can use any Linux distribution preferably Debian or Arch-based distribution as most of them comes with the above libraries pre-installed. 

Finally, If nothing work, you can try working in online [server](https://colab.research.google.com/notebooks/welcome.ipynb)
