### ISSUE TITLE
 Network architecture problem

### ISSUE THREAD

**Issue by Rashed-Alom** [Mahedi-61/MIU_Fall_2019#17]
relu problem..... 
![111](https://user-images.githubusercontent.com/38605227/69474378-bba6ca80-0dea-11ea-9543-e8f158e14760.PNG)
![222](https://user-images.githubusercontent.com/38605227/69474380-be092480-0dea-11ea-86c8-b0f1455c4093.PNG)

**Comment by Mahedi-61** [comment]
It's not due to adding activation function relu. 

You wrote
if __name__ == "__main__"
within the function space. 
Unindent a tab space from it.

**Comment by Rashed-Alom** [comment]
thank you sir.... Everything is ok now.....
