### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by RaisaAkter** [Mahedi-61/MIU_Fall_2019#2]
I have downloaded the data set in my computer. As my RAM is 4GB I need to split the data set for running the code. But I'm not clear with this data splitting techniques. Need help.

**Comment by Mahedi-61** [comment]
That's not so difficult to understand.
I think, having RAM 4GB is enough for training. But, for testing, you will have to split it a little bit. 

it's fairly easy to calculate. 

All the images of CIFAR-10 dataset are (32 x 32 x 3) dimensional 
Usually Python stores one integer into = 4 Byte.
So, for 50,000 training images you need = 50000 x  (32 x 32 x 3) x 4   Byte
                                                                        = 614400000 / (1024 * 1024) MB
                                                                        = 585.93 MB
Therefore, a process which requires 585.93 MB space in RAM shouldn't have any problem to run.

But, for 300,000 testing images you need = 300000 x  (32 x 32 x 3) x 4   / (1024*1024) MB
                                                                         = 3515.625 MB 
This process will not run. 
So, you can split the set into four parts each having 50,000 test images and load one after another.

See the following dummy code. 
```
first_index = 1; second_index = 50000
img_files= [TEST_DATA_DIR + str(i) +  
                    ".png"  for i in range(first_index, (second_index + 1))]

test_data = np.ndarray(((second_index - first_index), IMG_SIZE,  IMG_SIZE, IMG_CHANNEL),
                 dtype = np.float32)

for i, img_file in enumerate(img_files):
        img = Image.open(img_file)
        test_data[i] = np.array(img)
```
You can now work with `test_data` to predict 50,000 samples. 
After that delete this variable and change the `first_index`  variable to 50,000 and
`second_index` value to 1,00,000 to work with second 50,000 samples.

**Comment by RaisaAkter** [comment]
I got it. Jazakallah.

**Comment by RaisaAkter** [comment]
I tried to run the code by splitting the test set but I got some issues and couldn't solve them. First one is that when I set the first_index=250001,second_index=300000; it shows an error(attached picture).
The second thing is that by running on splitting test set I got multiple csv file. When I want to concatenate all csv file into one file, the id column of final csv file is repeating. The id suppose to start from 1 and end with 300000 but it is repeated between 1-50000 and I don't understand how to change the id. I searched in the google but didn't find any solution.
![keyError](https://user-images.githubusercontent.com/26532434/68081842-81c35380-fe3e-11e9-86d0-d2961465667b.png)

**Comment by Mahedi-61** [comment]
For First issue, You need to change first_index =   250000 and second_index = 299999 

As you see in code i have already add 1 in second_index variable. 

For second problem please paste your code. It’s not clear without code where 
you do mistake.

**Comment by RaisaAkter** [comment]
The second problem is solved. In case of first issue, I tried by setting first_index = 250001 and second_index = 299999 as in previous iteration I used second_index=250000 but got error(attached picture).The code is given below

first_index =  250001
second_index = 299999
test = pd.read_csv('test.csv')
test_image = []
for i in tqdm(range(first_index,(second_index+1))):
    img = image.load_img('test/'+test['id'][i].astype('str')+'.png', target_size=(28,28,3))
    img = image.img_to_array(img)
    img = img/255
    test_image.append(img)
y = np.array(test_image)

![image](https://user-images.githubusercontent.com/26532434/68211920-ad8f3680-0002-11ea-8a14-2cfd10f3a23e.png)

**Comment by Mahedi-61** [comment]
Clearly, The error comes up from the Pandas library when you are trying to assign or access values that are out of the index. 

Firstly, Where do you find "test.csv" file. 
Why do you create this?
If you want to iterate from 250000 to 299999 why don't you simply use for loop? 
Why do you need to access the dataframe's ID column to simply iterate some numbers? 

Anyway, you can manually check your test.csv file's maximum ID to locate the index problem

**Comment by Mahedi-61** [comment]
Clearly, The error comes up from Pandas library when you are trying to assign or access values that are out of the index. 

Firstly, Where do you find "test.csv" file. 
Why do you create this?
If you want to iterate from 250000 to 299999 why don't you simply use for loop? 
Why do need to access the dataframe's ID column to simply iterate some numbers? 

Anyway, you can manually check your test.csv file's maximum ID to locate the index problem

**Comment by RaisaAkter** [comment]
Actually I followed a blog and the instruction in it. I modified the 1 line and deleted the test.csv and finally it worked.
I think I need more study on python.
