### ISSUE TITLE
Error while finding module

### ISSUE THREAD

**Issue by shakib77** [Mahedi-61/MIU_Fall_2019#30]
![2019-12-03 00_23_37-Window](https://user-images.githubusercontent.com/32757305/69984390-3e562500-1563-11ea-94d5-5b7cdec7db95.png)
how to solve this?

**Comment by Mahedi-61** [comment]
When you run python code in module format you have to omit ` .py` extension. So, it's
`python3 -m project.config`

Then, You have to move one step back up i.e. you have to run it in your` ~/Desktop` directory.

**Comment by shakib77** [comment]
thank you sir
