### ISSUE TITLE
Tensorflow

### ISSUE THREAD

**Issue by Rokon-556** [Mahedi-61/MIU_Fall_2019#33]
how to work with tensorflow in virtual environment?????

**Comment by mzminhaz5683** [comment]
[virtualenv_Python_linux.pdf](https://github.com/Mahedi-61/MIU_Fall_2019/files/3920505/virtualenv_Python_linux.pdf)

follow this... main work of it:
1. install virtual environment by typing in terminal : sudo pip install virtualenv
2. enter the sudo password
3. create a folder called env by : mkdir env
4. Wait for finish and then type : cd env
5. open a terminal in it and type in terminal : which python3
6. copy the given path in the terminal. (Example: /usr/bin/python3)
7. type in the terminal: "virtualenv my_py --python=" and pest the path you have copied (Example: virtualenv my_py --python=/usr/bin/python3)
8. Now create a folder by : mkdir project
9. Now follow as sir said in tutorial. here project is the folder where sir puts all other files. like src, config etc
10. Note: for every time when you have to type anything in terminal first active the environment by typing : source my_py/bin/active
11. to deactive the environment you can close the terminal or type: deactivate

if you have still any problem then make comment with screenshot. That's easy to understand

**Comment by meharub** [comment]
Try installing python 3.6.5 on your windows environment .....hope your problem will be solved
