### ISSUE TITLE
Module Problem

### ISSUE THREAD

**Issue by Rokon-556** [Mahedi-61/MIU_Fall_2019#35]
Sir we have written all of codes according your videos.But whenever we want to run that we are facing problem like that.
![module-prblm](https://user-images.githubusercontent.com/55800719/70129114-5f745e00-16a8-11ea-926e-759b06fc13e7.PNG)

**Comment by mzminhaz5683** [comment]
you have to run the code in where project folder is located.... By the way you are using windows and you never said that both of your previous issues. The virtualenv will not work for any windows OS.

Now, it this case..... you are calling python in the location : "C:/git/Rokon-Rahman". 
So you must have a folder called project in the folder "Rokon-Rahman" to run.

I can't find whats going on there in your pc.. You should explain more about your problem.
use this key:
Type "tree /f" in this power shell and take a screenshot of the result. and upload that. It will show which files and folders are in the folder

**Comment by Mahedi-61** [comment]
May be `__init__.py` file is missing??
