### ISSUE TITLE
VirtualBox shut down!!

### ISSUE THREAD

**Issue by shakib77** [Mahedi-61/MIU_Fall_2019#6]
![2019-11-14 19_49_56-](https://user-images.githubusercontent.com/32757305/68862842-61d24080-0718-11ea-89e3-303d5ffb5851.png)
When ever i try to code with vs code it shows this again and again!! can anyone solve this?

**Comment by Mahedi-61** [comment]
check [this](https://forums.virtualbox.org/viewtopic.php?f=3&t=86614)

Otherwise, as this problem is related to windows application error, ask this question in Windows or Virtualbox Forum.

**Comment by shakib77** [comment]
sir, can i use parrot os for this project?

**Comment by shakib77** [comment]
thank you sir. i m checking it. can i use parrot os for this project ?

**Comment by Mahedi-61** [comment]
You can use any OS as you like. 
If you install Python version 3, Pip 3, Tensorflow, Keras, you are good to go. 

Since Parrot is a Debian-based distribution, you can also use all of my Linux command shown in the video tutorial.

**Comment by shakib77** [comment]
okay sir
